# .github/workflows/bot-restart.yml
name: Telegram Bot Auto Restart

on:
  schedule:
    # Run the workflow every 6 hours
    - cron: "0 */6 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the bot
      run: |
        python bot.py
        
